// Polygon drawing actions
export const START_DRAWING = 'START_DRAWING'
export const ADD_DRAWING_POINT = 'ADD_DRAWING_POINT'
export const FINISH_DRAWING = 'FINISH_DRAWING'
export const CANCEL_DRAWING = 'CANCEL_DRAWING'
export const SAVE_CADASTRAL_AREA = 'SAVE_CADASTRAL_AREA'
export const DELETE_CADASTRAL_AREA = 'DELETE_CADASTRAL_AREA'
export const SET_DRAWING_MODE = 'SET_DRAWING_MODE'

// Map layer actions
export const SET_MAP_LAYER = 'SET_MAP_LAYER'
